### PR TITLE
added Lumen extension

### PR DESCRIPTION
**Pull request by mikeerickson**
Modified the Laravel extension, creating a new Lumen extension.

This extension shall be used in place of Laravel extension when using Integrated with Lumen.

### CODE REVIEW

**Comment by mikeerickson** [comment]
@JeffreyWay So, did this PR not meet your guidelines?   What have I missed here?  I have identified an issue, fixed the issue and then it goes NOWHERE?

**Comment by laracasts** [comment]
Well, my grandmother died. So thanks. 

You just duplicated the file, and changed the extended class?? That's not the way to go about it. We'll extract a trait instead.

**Comment by mikeerickson** [comment]
First of all, sorry to hear about your grandmother.   My uncle died yesterday.  

My whole point was trying to help, and I didn't just duplicate and change the class.  

I won't bother offering to help with this in the future.  

Good luck!

**Comment by JeffreyWay** [comment]
Sorry to hear about your cousin and uncle dying. :(

The Lumen extension is now available. Just extend `Laracasts\Integrated\Extensions\Lumen` from your `TestCase` class.

**Pull request closed without merging**
