### PR TITLE
Add support for headers

### PR DESCRIPTION
**Pull request by Flambe**
I'm trying to test an API which checks the users session via an Authorization header. I can't see any way of specifying headers though, would it be possible to add one?

### CODE REVIEW

**Comment by mikeerickson** [comment]
+1  Currently having to use Guzzle in cases where I need to customize the header.

**Comment by JeffreyWay** [comment]
Do we have to do that HTTP_ clean part?

**Comment by Flambe** [comment]
@JeffreyWay Symfony seems to presume that all headers are prefixed with HTTP_,   though there does seem to be a few exceptions like the content headers in that file, which I should probably check for first. 

https://github.com/symfony/HttpFoundation/blob/master/ServerBag.php#L33

**Comment by Flambe** [comment]
I've made a few updates so that it merges with existing headers & so that it doesn't add HTTP to CONTENT headers.

**Pull request merged**
